/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package stoppowgui;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JFrame;

import cStopPow.*;

import SciTK.ExtensionFileFilter;
import SciTK.Dialog_Error;
import SciTK.Dialog_Prompt;
import SciTK.Prompt_Value;
import java.awt.event.KeyAdapter;
import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

class ModelEntry extends java.lang.Object
{
    public ModelEntry(String name_in, String model_name_in, StopPow model_in, String info_in)
    {
        name = name_in;
        model = model_in;
        model_name = model_name_in;
        info = info_in;
    }
    public String name;
    public String model_name;
    public StopPow model;
    public String info;
}
/**
 *
 * @author alex
 */
public class ModelManagerGUI extends javax.swing.JFrame {

    /**
     * Creates new form ModelManagerGUI
     */
    public ModelManagerGUI(JFrame parent) {
        // initialize the model storage Map:
        models = new HashMap<String,ModelEntry>();
        
        // set up GUI components:
        initComponents();
        
        setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        pack();
        setLocationRelativeTo(parent);
        // start hidden:
        setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        model_table = new javax.swing.JTable();
        menu_bar = new javax.swing.JMenuBar();
        menu_add = new javax.swing.JMenu();
        menu_add_srim = new javax.swing.JMenuItem();
        menu_add_lipetrasso = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        model_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Type", "Info"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        model_table.setShowGrid(false);
        model_table.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(model_table);
        model_table.getColumnModel().getColumn(0).setPreferredWidth(50);
        model_table.getColumnModel().getColumn(1).setPreferredWidth(50);
        model_table.getColumnModel().getColumn(2).setPreferredWidth(200);
        // add a keylistener for delete:
        model_table.addKeyListener (new KeyAdapter(){
            @Override
            public void keyReleased(KeyEvent e)
            {
                if( e.getKeyCode() == KeyEvent.VK_DELETE
                    || e.getKeyCode() == KeyEvent.VK_BACK_SPACE )
                remove_from_table( model_table.getSelectedRow() );
            }
        });

        menu_add.setText("Add...");
        menu_add.setToolTipText("Add a stopping power model");

        menu_add_srim.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        menu_add_srim.setText("SRIM");
        menu_add_srim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_add_srimActionPerformed(evt);
            }
        });
        menu_add.add(menu_add_srim);

        menu_add_lipetrasso.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        menu_add_lipetrasso.setText("Li-Petrasso");
        menu_add_lipetrasso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_add_lipetrassoActionPerformed(evt);
            }
        });
        menu_add.add(menu_add_lipetrasso);

        menu_add.setMnemonic(KeyEvent.VK_A);

        menu_bar.add(menu_add);

        setJMenuBar(menu_bar);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(10, 10, 10)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 375, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(5, 5, 5)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 220, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_add_lipetrassoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_add_lipetrassoActionPerformed
        // since this runs in the event dispatch thread, it is best to wrap
        // into invokeLater:
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                add_LiPetrasso();
            }
        });
    }//GEN-LAST:event_menu_add_lipetrassoActionPerformed

    private void menu_add_srimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_add_srimActionPerformed
        // since this runs in the event dispatch thread, it is best to wrap
        // into invokeLater:
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                add_SRIM();
            }
        });
    }//GEN-LAST:event_menu_add_srimActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu menu_add;
    private javax.swing.JMenuItem menu_add_lipetrasso;
    private javax.swing.JMenuItem menu_add_srim;
    private javax.swing.JMenuBar menu_bar;
    private javax.swing.JTable model_table;
    // End of variables declaration//GEN-END:variables

    // ---------------------------------------
    //       Manage the models
    // ---------------------------------------
    private Map<String,ModelEntry> models;
    
    public ArrayList<StopPow> get_models()
    {
        // build an ArrayList to return:
        ArrayList<StopPow> ret = new ArrayList<StopPow>();
        
        // iterate over all values in the Map and add to the ArrayList:
        for( Map.Entry<String,ModelEntry> row : models.entrySet() )
        {
            // have to get the "value" from the Map, then the model
            // from it (since each value is a ModelEntry object)
            ret.add( row.getValue().model );
        }
        
        return ret;
    }        

    // ---------------------------------------
    //   Manage the table display of models
    // ---------------------------------------
    private void add_to_table(ModelEntry row)
    {
        // get number of rows:
        int rows = model_table.getRowCount();
        int index = rows+1;
        DefaultTableModel table_data = (DefaultTableModel)model_table.getModel();
        Object[] table_row = { row.name , row.model_name , row.info };
        table_data.addRow( table_row );
    }
    private void remove_from_table(int index)
    {
        // get number of rows:
        int rows = model_table.getRowCount();
        // sanity check:
        if( index < 0 || index >= rows )
            return;
        
        // get access to underlying table data:
        DefaultTableModel table_data = (DefaultTableModel)model_table.getModel();
        // get the name of the row to delete:
        String row_name = (String)table_data.getValueAt(0, index);
        
        // remove from the internal storage:
        models.remove(row_name);
        // remove from displayed table:
        table_data.removeRow(index);
    }
    
    // ---------------------------------------
    //       Handlers for adding models
    // ---------------------------------------
    private void add_SRIM()
    {
        // Choose a file:
        JFileChooser fc = new JFileChooser();
        fc.addChoosableFileFilter(new ExtensionFileFilter("txt", new String[] {"txt,TXT"}));
        fc.addChoosableFileFilter(new ExtensionFileFilter("zig", new String[] {"zig,ZIG"}));
        // remove default option:
        fc.setAcceptAllFileFilterUsed(false);
        
        // Select a file using the JFileChooser dialog:
        int fc_return = fc.showOpenDialog(ModelManagerGUI.this);
        
        // if the user actually wants to load an SRIM file:
        if( fc_return==JFileChooser.APPROVE_OPTION )
        {
            
            //get the file:
            File srim_file = fc.getSelectedFile();
            
            // try to create a new model
            StopPow new_model;
            try
            {
                 new_model = new StopPow_SRIM( srim_file.getAbsolutePath() );
            }
            catch( IOException e )
            {
                Dialog_Error d = new Dialog_Error("Error opening SRIM file." 
                        + '\n' + e.getMessage());
                return;
            }
            
            // get the name, which we require non-empty and unique:
            String name = "";
            while( name.equals("") || models.containsKey(name) )
            {
                Dialog_Prompt d2 = new Dialog_Prompt("Model name: ");
                name = d2.get_value().get_value_str();
                
                // if the user canceled, then cancel creating the model:
                if( !d2.get_accepted() )
                    return;
                
                // throw error dialogs to help user if necessary:
                if( name.equals("") )
                {
                    Dialog_Error e1 = new Dialog_Error(" Name cannot be empty! ");
                }
                if( models.containsKey(name) )
                {
                    Dialog_Error e2 = new Dialog_Error(" Name must be unique! ");
                }
            }
            
            // Construct an info string array
            // For SRIM, just the file path for now:
            String info = srim_file.getAbsolutePath();
            
            // add to the class:
            ModelEntry new_entry = new ModelEntry(name,"SRIM",new_model,info);
            models.put(name, new_entry);
            
            // add to the table:
            add_to_table(new_entry);
        }
    }
    
    private void add_LiPetrasso()
    {
        // use our custom L-P dialog:
        LPDialog d = new LPDialog(ModelManagerGUI.this,true);
    }
}
